---
- name: Determine the running kernel release
  command: uname -r
  register: kernel_release



# Using with_items loop for apt module is deprecated
- name: Install WireGuard and other requirements
  become: true
  become_user: root
  package:
    name:
      - linux-headers-{{ kernel_release.stdout }}
      - linux-headers-generic
      - wireguard
      - wireguard-dkms
      - wireguard-tools
#      - python2.7
    state: present
    