---
- name: Install wireguard and other prequisites on the server
  include: 'install_wireguard.yml'
  tags: install_wireguard



- name: Generate client keys and enable wireguard interface
  become: true
  include: 'generate_keys.yml'
  tags: generate_keys

- name: Set up nat and firewall rules
  become: true
  include: 'nat_firewall.yml'
  tags: nat_firewall

- name: Download client configs
  become: true
  become_user: root
  include: 'download_configs.yml'
  tags: download_configs